name: AIX_Openxl_CI
on: [push] # Triggers the workflow on push events

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Trigger Jenkins Job via API
      shell: bash # Ensures the same syntax works on Windows
      run: |
        curl -X POST -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
        "${{ secrets.JENKINS_URL }}/job/onnxruntime-aix-local/build"
        parameters: |
          ENVIRONMENT=staging
          VERSION=${{ github.sha }}
